AWSTemplateFormatVersion: 2022-14-05
Description: "S3 Bucket, Route53, S3 policy"

Parameters:
    DomainName:
        Type: String
        Description: The DNS name of an existing Amazon Route 53 hosted zone
    BucketName:
        Type: String
        Description: Amazon S3 files bucket name
    HostedZoneId:
        Type: String
        Description: Amazon Route53 Hosted Zone Id for DomainName
        AllowedPattern : (?!-)[a-zA-Z0-9-.]{1,63}(?<!-),
        ConstraintDescription : must be a valid DNS zone name
    CertificateArn:
        Type: String
        Description: Certificate Link
        
 Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Description: Creating Amazon S3 bucket from CloudFormation
        Properties:
            AccessControl: Private
        Tags:
            - Key: Name
            Value: !Ref BucketName
    ACMCertificate: 
        Type: "AWS::CertificateManager::Certificate"
        Properties: 
            DomainName: example.com
            DomainValidationOptions:
                - DomainName: !Ref DomainName
                  HostedZoneId: !HostedZoneId
            ValidationMethod: DNS
    Domain:
        Type: 'AWS::SDB::Domain'
        Properties:
    RouterZone:
        Type: 'AWS::Route53::HostedZone'
        Properties:      
    CloudFront:
        Type: 'AWS::CloudFront::Distribution'
        Properties: 

      
 Outputs:
    CloudFront:
        Description: output id CloudFront
        Value:
    StackVPC:
        Description: The ID of the VPC
        Value: !Ref MyVPC
        Export:
            Name: !Sub "${AWS::StackName}-VPCID"
    S3Bucket:
        Description: Bucket Created using this template.
        Value: !Ref S3Bucket
